package shared

type StatusType int

const (
	AuthToken = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImVqYlZ0M2V1WWVfcy13ZlBvc0hiTUF3eno1OFA1a0N3NUNGSmFEb2kyWjQ9In0.eyJhdWQiOiJhcHBzIiwiY2xpZW50SWQiOiJociIsImRpc3BsYXlOYW1lIjoiRGVkZSBUaWEiLCJlbWFpbCI6ImRlZGVlZTI4QGdtYWlsLmNvbSIsImVtcGxveWVlSWQiOjEzNjI3MiwiZXhwIjoxNjU2NjE0Mjk2LCJncm91cCI6ImhyIiwiZ3JvdXBzIjpbImRlZmF1bHQiXSwiaWF0IjoxNjU2NTg1NDk2LCJpc3MiOiJzaWNlcGF0IiwibmlrIjoiMjEwNzIyMDUiLCJwb2xpY3kiOiJociIsInJvbGVzIjpbImRlZmF1bHQiXSwic3ViIjoiMk1GaGM2Z3FUNkNraTZyUXliUFJmeGhDd3RNc014bVpmSlNOak1rZjM4TGEiLCJ0eXBlIjoiaW50ZXJuYWwiLCJ1c2VySWQiOjEzMzg5NywidXNlcm5hbWUiOiIyMTA3MjIwNSJ9.fsoOcErGOWkZ1u7jEydz43tGVH9qVzfHdZO8Hum3sj0tRLMr5YJ9ZKh6Qn1rXc0fBMiEXxO0hE3KQ6o6i3RjgwfefT5CYH81NGlf6FanXyG58oE-sSGpa0GledpFJUOgCMYDmdcly67uecnFvY6Bie3izH5BZcNN15iHPIq9sthHvv7PslNlPeL8pqPmrElzG8brjsd8_EZXrnsy-ULSs7Y85rbjE7hA8g2GJ9aIWEo3lEjuj-oBn6qOfj5aP8N-F2ILDS02PkegEIVOBevUbqmoIchQMVHEbd9OU_5nHrL_wfZ_fYs4BgD3bwyTkE15f3aOio3zP2q8eeaPjXIqHA"
)

const (
	StatusImported StatusType = iota
	StatusFinished
	StatusFailInMasterData
	StatusFailInAuth
	StatusFailInAuthz
)

func (s StatusType) String() string {
	status := [...]string{
		"data imported",
		"data finished",
		"data failed to process in masterdata service",
		"data failed to process in authentication service",
		"data failed to process in authorization service",
	}
	return status[s]
}
