package shared

type StatusType int

const (
	AuthToken = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRXMWRTbnV4ejJiZWRvZGFvZ2h6Q3FMdVk2aGZqYU5KZS1SNXNRZkRGdms9In0.eyJhdWQiOiJhcHBzIiwiY2xpZW50SWQiOiJ1bXMiLCJkaXNwbGF5TmFtZSI6IkRlZGUgVGlhIiwiZW1haWwiOiJERURFRUUyOEBHTUFJTC5DT00iLCJlbXBsb3llZUlkIjoxMzYyNzIsImV4cCI6MTY0OTQ0NDQ0MCwiZ3JvdXAiOiJ1bXMiLCJncm91cHMiOlsiZGVmYXVsdCJdLCJpYXQiOjE2NDk0MTY0NDAsImlzcyI6InNpY2VwYXQiLCJuaWsiOiIyMTA3MjIwNSIsInBvbGljeSI6InVtcyIsInJvbGVzIjpbImRlZmF1bHQiXSwic3ViIjoiMk1GaGM2Z3FUNkNraTZyUXliUFJmeGhDd3RNc014bVpmSlNOak1rZjM4TGEiLCJ0eXBlIjoiaW50ZXJuYWwiLCJ1c2VySWQiOjEzMzg5NywidXNlcm5hbWUiOiIyMTA3MjIwNSJ9.C9zSAUTipCJOz-Ug_PDBcncPkmjN9wOePiUrMCpftTtXj_eSNbHlbYJXc6t0xxfUPpdht_r471hWbR1ktm398HN_uW-aXvpLPxvnkAmMdI5nC2slflCSZOhcoKsS6qgxw4Doacw2ViVmlnDgptNfkmy2sprSNXhwRfhpqu7k3H5Wsd54-5TxWGbsBi3-JO1wDaU1cpJ2ZC0NqLNRuFdkxPS55RQM0he3gOPmCrWs-ysRxbAy8qTQkfw6h8ZNF6CYXeuPH8xU_wJTd41CbvBwbUZQ_j3I7DJBQhMvkGBLFjJS7_hx6kNdfJRsA49MXTZhjkBJ_9ytKAiUeFURGTi7lA"
)

const (
	StatusImported StatusType = iota
	StatusFinished
	StatusFailInMasterData
	StatusFailInAuth
	StatusFailInAuthz
)

func (s StatusType) String() string {
	status := [...]string{
		"data imported",
		"data finished",
		"data failed to process in masterdata service",
		"data failed to process in authentication service",
		"data failed to process in authorization service",
	}
	return status[s]
}
