package shared

type StatusType int

const (
	AuthToken = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImU5b2g1bmRGa2JHZ1NJMy14TGU0ZS1RMzBZdU0tSmNwbDhoWE5qOGlrSHc9In0.eyJhdWQiOiJhcHBzIiwiY2xpZW50SWQiOiJociIsImRpc3BsYXlOYW1lIjoiU3VjaSBOb3ZpYW50aSIsImVtYWlsIjoic3VjaS5ub3ZpYW50aUB5YWhvby5jby5pZCIsImVtcGxveWVlSWQiOjI5NzIyLCJleHAiOjE2NDMxMjgxNjQsImdyb3VwIjoiaHIiLCJncm91cHMiOlsiZGVmYXVsdCJdLCJpYXQiOjE2NDMwOTkzNjQsImlzcyI6InNpY2VwYXQiLCJuaWsiOiIyMDA1MDE2MCIsInBvbGljeSI6ImhyIiwicm9sZXMiOlsiZGVmYXVsdCJdLCJzdWIiOiJIelRRVWpBRTN2VlljVThnb0I3eUp4N1BaaHBwWDd1NHI3QkNyM3gzREV2UyIsInR5cGUiOiJpbnRlcm5hbCIsInVzZXJJZCI6MjcyMTksInVzZXJuYW1lIjoiMjAwNTAxNjAifQ.e8QMl-uNakABGBqm8G9FX3oKUhPJ-1WWeHqKmcvT6L8QGAXBP_n2kH5jKJ_pd5tkXRpy0PakYwuBqvUnNzoNyXe9od7T3R7ubKFV8lSmdRwokZb7TWrLudHhILSqGGnBL-nOnBdPQM6Lc-jVqhson1cNQY4V89O2FeGV0DTzClzxK45dZ9jbd660NSV1lLw3KU5ry7ovgSDCdFQI6bqzcxXj_8duWUUSvW7p4sbyMLeM1feexk_wa00dXj6dIVrLh0Z90D3Ip4ppoUDeu_UFiBAO5pCz5Lt8zvxBlCAimESaAAK2opAuNRbz1zZYG_ANPOKzbbiLUcdPdzgNlFAshg"
)

const (
	StatusImported StatusType = iota
	StatusFinished
	StatusFailInMasterData
	StatusFailInAuth
	StatusFailInAuthz
)

func (s StatusType) String() string {
	status := [...]string{
		"data imported",
		"data finished",
		"data failed to process in masterdata service",
		"data failed to process in authentication service",
		"data failed to process in authorization service",
	}
	return status[s]
}
